kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: bc-microfrontend-angular-container
  namespace: microservices
  labels:
    name: microservices
    app.kubernetes.io/part-of: microservices
spec:
  resources:
    limits:
      ephemeral-storage: 8Gi
    requests:
      ephemeral-storage: 4Gi
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'is-microfrontend-angular-container:latest'
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile-microfrontend-angular-container-openshift
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/dey600r/NETBase.git'
      ref: master
  triggers:
    - type: ConfigChange
  runPolicy: Serial