

kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: is-microfrontend-angular-container
  namespace: microservices
  labels:
    app: microservices
    app.kubernetes.io/part-of: microservices