FROM node:22.22.0-alpine3.22 as build

WORKDIR /app
RUN echo "INSTALL LIBRARIES"
COPY ./Frontend/angular-microfrontend/home-module/package*.json ./
RUN npm install

RUN echo "BUILD PROD"
COPY --chown=node ./Frontend/angular-microfrontend/home-module .
RUN npm run build-prod

# Stage 2: Serve app with nginx server
# FROM nginxinc/nginx-unprivileged

# COPY /Utils/docker-configs/nginx-def.conf /etc/nginx/conf.d/default.conf

# COPY --from=build /app/dist/ /usr/share/nginx/html

# EXPOSE 2005:3300
# CMD ["nginx", "-g", "daemon off;"]

# Stage 2: Serve app with serve server
FROM node:22.22.0-alpine3.22

WORKDIR /app
RUN npm install -g serve
COPY --from=build /app/dist/ /app
EXPOSE 2005:3300
CMD ["serve", "-s", ".", "-l", "3300"]