FROM node:22.22.0-alpine3.22 as build

WORKDIR /app
RUN echo "INSTALL LIBRARIES"
RUN mkdir -p ../app-container/libs
#COPY ./Frontend/angular-microfrontend/app-container/libs/security-lib-0.1.6.tgz ../app-container/libs
COPY ./Frontend/angular-microfrontend/security-module/package*.json ./
COPY ./Frontend/angular-microfrontend/app-container/.npmrc /root/

RUN echo "//nexus.apps-crc.testing/repository/npm-microfrontend/:_authToken=${NPM_TOKEN}" >> /root/.npmrc
RUN npm install

RUN echo "BUILD PROD"
COPY --chown=node ./Frontend/angular-microfrontend/security-module .
RUN npm run build-prod

# Stage 2: Serve app with nginx server
FROM nginxinc/nginx-unprivileged

COPY /Utils/docker-configs/nginx-def.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/security-module/ /usr/share/nginx/html

EXPOSE 2002:3300
CMD ["nginx", "-g", "daemon off;"]