FROM node:18.16.0-alpine3.17
RUN mkdir -p /opt/app
WORKDIR /opt/app
COPY ./Backend/MicroservicesBackend/Microservice.SettingApi/package.json ./Backend/MicroservicesBackend/Microservice.SettingApi/package-lock.json ./Backend/MicroservicesBackend/Microservice.SettingApi/tsconfig.json .
RUN npm install
COPY ./Backend/MicroservicesBackend/Microservice.SettingApi/src/ .
RUN npm run build
EXPOSE 3800
CMD [ "npm", "start"]