FROM node:18.16.0-alpine3.17
USER root
RUN mkdir -p /opt/app
WORKDIR /opt/app
RUN chmod -R 777 ./
ENV NODE_ENV openshift
COPY ./MicroservicesBackend/Microservice.SettingApi/package.json ./MicroservicesBackend/Microservice.SettingApi/package-lock.json ./MicroservicesBackend/Microservice.SettingApi/tsconfig.json .
RUN npm cache clean --force
RUN npm install -g npm@latest --force
RUN npm i
COPY ./MicroservicesBackend/Microservice.SettingApi/src/ .
RUN npm run build
EXPOSE 3800
CMD [ "npm", "start", "--loglevel=verbose"]

