#FROM node:16-bullseye-slim
#FROM node:18.16.0-alpine3.17
FROM registry.access.redhat.com/ubi8/nodejs-18:1-71.1695741533

USER root
RUN npm install -g http-server

USER node
RUN mkdir -p /home/node/app /tmp/app
WORKDIR /tmp/app

COPY --chown=node ./Frontend/angular-frontend-keycloak .

ENV NODE_OPTIONS=--max-old-space-size=8192
RUN echo "NodeJS $(node -v) memory config:" && node -p "v8.getHeapStatistics()"
RUN npm i
RUN npm run build-prod && mv dist/angular-frontend-keycloak/* /home/node/app && rm -fr /tmp/app

WORKDIR /home/node/app

EXPOSE 3000

CMD [ "http-server", "-p 3000", "./" ]

