FROM node:22.22.0-alpine3.22 as build

WORKDIR /app
RUN echo "INSTALL LIBRARIES"
RUN mkdir -p ./libs
COPY ./Frontend/angular-microfrontend/app-container/package*.json ./
COPY ./Frontend/angular-microfrontend/app-container/.npmrc ./

RUN echo "//nexus.apps-crc.testing/repository/npm-microfrontend/:_authToken=${NPM_TOKEN}" >> .npmrc
RUN cat .npmrc
RUN npm install

RUN echo "PACK"
COPY --chown=node ./Frontend/angular-microfrontend/app-container .
RUN npm run pack

RUN echo "PUBLISH"
WORKDIR /app/dist/security-lib
RUN npm publish
RUN rm -f /app/.npmrc

CMD ["echo", "Library published"]