FROM node:18.16.0-alpine3.17
RUN mkdir -p /opt/app
WORKDIR /opt/app
ENV NODE_ENV openshift
COPY ./MicroservicesBackend/Microservice.SettingApi/package.json ./MicroservicesBackend/Microservice.SettingApi/tsconfig.json .
RUN npm install
COPY ./MicroservicesBackend/Microservice.SettingApi/src/ .
RUN npm run build
RUN sudo chown -R 1000690000:0 "./"
EXPOSE 3800
CMD [ "npm", "start"]