nameOverride: ""

# DEPLOYMENT CONFIG
deployment:
  replicas: 1
  annotations: 
    connectsTo:
  labels:
    runtime: nodejs
  image:
    repository: image-registry.openshift-image-registry.svc:5000
    tag: latest
  resources:
    limits:
      ephemeral-storage: 8Gi
    requests:
      ephemeral-storage: 4Gi
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
  policy: Always

# BUILD CONFIG
build:
  source:
      type: Git
      git:
        uri: 'https://github.com/dey600r/NETBase.git'
        ref: master
  triggers:
      type: ConfigChange

# SERVICE
service:
  type: ClusterIP
  port: 3300
  protocol: TCP
  portName: fr-home-port

#ROUTE
route:
  enabled: true
  domain: "apps-crc.testing"

#CONFIGMAPS
configmapEnv:
  enabled: false

configmapVolume:
  enabled: false

#SECRET
secret:
  enabled: false