nameOverride: ""

# DEPLOYMENT CONFIG
deployment:
  replicas: 1
  annotations: 
    connectsTo:
      - apiVersion: apps/v1
        kind: Deployment
        name: keycloak
      - apiVersion: apps/v1
        kind: Deployment
        name: dp-microservice-maintenance
      - apiVersion: apps/v1
        kind: Deployment
        name: dp-microservice-vehicle
      - apiVersion: apps/v1
        kind: Deployment
        name: dp-microservice-security
  labels:
    runtime: dotnet
  image:
    repository: image-registry.openshift-image-registry.svc:5000
    tag: latest
  resources:
    limits:
      ephemeral-storage: 8Gi
    requests:
      ephemeral-storage: 4Gi
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
  policy: Always

# BUILD CONFIG
build:
  source:
      type: Git
      git:
        uri: 'https://github.com/dey600r/NETBase.git'
        ref: master
  triggers:
      type: ConfigChange

# SERVICE
service:
  type: ClusterIP
  port: 8080
  protocol: TCP
  portName: gateway-port

#ROUTE
route:
  enabled: true
  domain: "apps-crc.testing"

#CONFIGMAP
configmap:
  enabled: true
  volume: false
  mountPath: 
  data:
    Keycloak__Authority: "https://keycloak-microservices.apps-crc.testing/realms/microservices"
    Keycloak__AuthorizationUrl: "https://keycloak-microservices.apps-crc.testing/realms/microservices/.well-known/openid-configuration"
    Keycloak__TokenUrl: "https://keycloak-microservices.apps-crc.testing/realms/microservices/protocol/openid-connect/token"
    Keycloak__Realm: "microservices"
    Keycloak__ClientId: "backend"
    keycloakEnabled: "true"

#SECRET
secret:
  enabled: true
  data:
    Keycloak__PublicKey: "MIICqTCCAZECBgGckL961DANBgkqhkiG9w0BAQsFADAYMRYwFAYDVQQDDA1taWNyb3NlcnZpY2VzMB4XDTI2MDIyNDE3NDEzM1oXDTM2MDIyNDE3NDMxM1owGDEWMBQGA1UEAwwNbWljcm9zZXJ2aWNlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALZ0yfOeF/PUifAvCSis1PcVuoYxkBIYwW25gfHzAg5tnz4jhRi0Z6Cxp+dFdke3wQg5RRtCPB7Gormk1Zt5ks0bNCZ6lWZhlotmMIJqyNr0smpnPa4KFagXnG+U46WHqWZoSX3BtUwR/bfhpjieDu9qijZyZvzigTsGj+YaETMvoFLsHuwjcOEuQwjSgZb0ZTA1u2813JQWUvFBZAAYwBp9uBjwLDNuZEqW3vaPIXWN8ypvvyENRUGb7skmDYv5QO1El/PkpoyjH2okLrYigLBOiezZtZbLM1dVbKoATDSqXQnw+f9f7J6lcoWeZ//2ywhIBBcY/9vFogpmVUysyfECAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAeyhwTxGtNaM8B73R23kvjAeY2jfiCEDjMh3FFDC8fHCk2Y85cet4L9rSleUyKOP6Dl+1VUPp+rohaSUVci3xYsM0TVbWm6Wy+00cdl5SHoEJb3bvwdFr4wILzBoQ+SlO1F3Mg2Asu6ReFumafTqJErrTJcRNihED5Jm/HChX6KyLyJjmaV/d8ZsbT2gQ9oNTr3Ng3WFto4cfHSG8iHX7BjkXPxu9n6+Esy2l/wLNe+72DsUMlHTsf2P7Nsm/j37jAZIpkk54jQPdNAvbvOk+uCBDT/H4SkGw/+WgboF6PYBOj6eJX2o/l2VbU5kwXu6ZdiJodv1WNj+oXMntovXdMA=="