nameOverride: ""

# DEPLOYMENT CONFIG
deployment:
  enabled: false
  image:
    repository: image-registry.openshift-image-registry.svc:5000
    tag: latest


# BUILD CONFIG
build:
  source:
      type: Git
      git:
        uri: 'https://github.com/dey600r/NETBase.git'
        ref: master
  triggers:
      type: ConfigChange

# SERVICE
service:
  enabled: false

#ROUTE
route:
  enabled: false

#CONFIGMAPS
configmapEnv:
  enabled: false

configmapVolume:
  enabled: false

#SECRET
secret:
  enabled: false

buildSecret:
  enabled: true
  data:
    NPM_TOKEN: NpmToken.cd98ad7e-76dc-3f67-ad12-cf55c6cd26d7