nameOverride: ""

# DEPLOYMENT CONFIG
deployment:
  replicas: 1
  annotations: 
    connectsTo:
      - apiVersion: apps/v1
        kind: Deployment
        name: dp-sql-server
  labels:
    runtime: dotnet
  image:
    repository: image-registry.openshift-image-registry.svc:5000
    tag: latest
  resources:
    limits:
      ephemeral-storage: 8Gi
    requests:
      ephemeral-storage: 4Gi
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
  policy: Always

# BUILD CONFIG
build:
  source:
      type: Git
      git:
        uri: 'https://github.com/dey600r/NETBase.git'
        ref: master
  triggers:
      type: ConfigChange

# SERVICE
service:
  type: ClusterIP
  port: 8080
  protocol: TCP
  portName: security-port

#ROUTE
route:
  enabled: false
  domain: "apps-crc.testing"

#CONFIGMAPS
configmapEnv:
  enabled: true
  data:
    ConnectionStrings__Encripted: "true"

configmapVolume:
  enabled: false

#SECRET
secret:
  enabled: true
  data:
    #ConnectionStrings__SqlServer: "Server=svc-sql-server.microservices.svc.cluster.local,1433;Database=SecurityDB;TrustServerCertificate=true;User Id=sa;Password=PassWord123?"
    ConnectionStrings__SqlServer: "wMQxWqixTNIuYQBt6hhWYYvLPR66q9ecz3Slvnn5kE8o9+4+KK22d3F9WSfo1+as0etk+UmKWP+FQDobh2Vxz4x4GHDSnQVyzz8s8BzV/gv/gycxopO3brwNJ7h36qusplvJ0c95V7n5na6zMO0RUAyt/0CSD2mVkD1+AeMsOLMv3P2PFwMO+Xg0RtB5X5Q4sxIGG4FNp9tzs75ATH+iTg=="