kind: Deployment
apiVersion: apps/v1
metadata:
  name: dp-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
    {{- include "microservice.labels.runtime" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        deployment: dp-{{ .Release.Name }}
    spec:
      {{- if .Values.persistenceClaim.enabled }}
      volumes:
        - name: {{ .Values.persistenceClaim.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistenceClaim.claimName }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.deployment.image.repository }}/{{ .Release.Namespace }}/is-{{ .Release.Name }}:{{ .Values.imageStream.tag }}
          env:
          {{- range .Values.deployment.env }}
            - name: {{ .name }}
              value: {{ .value }}
          {{- end }}
          ports:
          {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
          {{- end }}
          {{- if .Values.persistenceClaim.enabled }}
          volumeMounts:
          {{- range .Values.persistenceClaim.mountPaths }}
            - name: {{ $.Values.persistenceClaim.name }}
              mountPath: {{ . }}
          {{- end }}
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: {{ .Values.deployment.policy }}
      restartPolicy: {{ .Values.deployment.policy }}
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  {{- with .Values.deployment.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600